### PR TITLE
Kylepres/dry dep

### PR DESCRIPTION
**Pull request by pressel**
This PR brings in the basic structure and first ported function of dry deposition. The ported function is gravit_settling_velocity.

### CODE REVIEW

**Review by odiazib — APPROVED** [review]
Looks good to me.

**Comment by jeff-cohere** [comment]
Looks like you need to merge some validation data first:

```
CMake Error: File /home/runner/work/mam4xx/mam4xx/src/validation/mam_x_validation/drydep/compare_drydep.py does not exist.
```

**Review by jeff-cohere — COMMENTED** [review]
Looks good to me too. Once you have validation data in place and tests pass, we're good to merge.

**Comment by pressel** [comment]
Thanks for the quick reviews, I think I have fixed the validation data issue.

**Review by jeff-cohere — APPROVED** [review]

**Pull request merged**
