### PR TITLE
Add Interface Pressure to atmosphere class.

### PR DESCRIPTION
**Pull request by overfelt**
This depends on a pull request to the haero repository so needs to be synchronized with that pull request and can not be merged until the haero change is merged to master.

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Looks like a runner/container failure on the PNNL side. Can you just rerun the failed job again?

**Comment by jeff-cohere** [comment]
The runs were all skipped for some reason in the PNNL Research Computing CI pipeline. I've tried to restart them on that end. @jaelynlitz , do you know if we have to make another commit before these tests can be run again?

**Comment by jaelynlitz** [comment]
> The runs were all skipped for some reason in the PNNL Research Computing CI pipeline. I've tried to restart them on that end. @jaelynlitz , do you know if we have to make another commit before these tests can be run again?

Looks like the runners are having issues getting started, I will reach out for help

**Comment by jaelynlitz** [comment]
> > The runs were all skipped for some reason in the PNNL Research Computing CI pipeline. I've tried to restart them on that end. @jaelynlitz , do you know if we have to make another commit before these tests can be run again?
> 
> Looks like the runners are having issues getting started, I will reach out for help

A kubernetes upgrade yesterday broke our (and others) HPC CI runners - a fix is out this morning and I have re-triggered the pipeline

**Comment by overfelt** [comment]
Any indication of why the pipeline failed?

**Comment by jaelynlitz** [comment]
Looks like the double precision builds are having problems -

The Debug mode build is throwing an error when compiling about running out of space on the device:
```
/qfs/projects/ops/rh7_gpu/gcc/10.2.0/include/c++/10.2.0/cmath(204): catastrophic error: error while writing generated C++ file: No space left on device
1 catastrophic error detected in the compilation of "/people/svceagles/gitlab/6197/haero_Debug_double/src/tests/conversions_unit_tests.cpp".
Compilation terminated.
gmake[2]: *** [src/tests/CMakeFiles/conversions_unit_tests.dir/conversions_unit_tests.cpp.o] Error 4
++ :
+++ awk 'BEGIN{i=0}/BUILD_STATUS/{i++}END{print i}' output
++ [[ 0 != \0 ]]
++ sleep 10
gmake[1]: *** [src/tests/CMakeFiles/conversions_unit_tests.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/qfs/projects/eagles/pnnl-ci/haero_Debug_double/include/spdlog/fmt/bundled/core.h(313): warning: unrecognized GCC pragma
/qfs/projects/ops/rh7_gpu/gcc/10.2.0/include/c++/10.2.0/cmath(204): catastrophic error: error while writing generated C++ file: No space left on device
1 catastrophic error detected in the compilation of "/people/svceagles/gitlab/6197/haero_Debug_double/src/tests/aero_modes_tests.cpp".
Compilation terminated.
gmake[2]: *** [src/tests/CMakeFiles/aero_modes_unit_tests.dir/aero_modes_tests.cpp.o] Error 4
gmake[1]: *** [src/tests/CMakeFiles/aero_modes_unit_tests.dir/all] Error 2
/qfs/projects/eagles/pnnl-ci/haero_Debug_double/include/spdlog/fmt/bundled/core.h(313): warning: unrecognized GCC pragma
In file included from tmpxft_000007fd_00000000-6_utils_unit_tests.cudafe1.stub.c:1:
/tmp/tmpxft_000007fd_00000000-6_utils_unit_tests.cudafe1.stub.c:87:27: fatal error: error writing to /tmp/cch8T0k7.s: No space left on device
   87 | #pragma GCC diagnostic pop
      |                           ^
compilation terminated.
```

The Release mode is compiling and most tests are passing but the job log is too long and I can't see after test 403 due to a huge printout of "input difference" in the validation test. I could potentially change the pipelines to run ctest non-verbosely then re-run failed tests with the verbose flag to prevent this in the future.

**Comment by jaelynlitz** [comment]
> Looks like the double precision builds are having problems -
> 
> The Debug mode build is throwing an error when compiling about running out of space on the device:
> 
> ```
> /qfs/projects/ops/rh7_gpu/gcc/10.2.0/include/c++/10.2.0/cmath(204): catastrophic error: error while writing generated C++ file: No space left on device
> 1 catastrophic error detected in the compilation of "/people/svceagles/gitlab/6197/haero_Debug_double/src/tests/conversions_unit_tests.cpp".
> Compilation terminated.
> gmake[2]: *** [src/tests/CMakeFiles/conversions_unit_tests.dir/conversions_unit_tests.cpp.o] Error 4
> ++ :
> +++ awk 'BEGIN{i=0}/BUILD_STATUS/{i++}END{print i}' output
> ++ [[ 0 != \0 ]]
> ++ sleep 10
> gmake[1]: *** [src/tests/CMakeFiles/conversions_unit_tests.dir/all] Error 2
> gmake[1]: *** Waiting for unfinished jobs....
> /qfs/projects/eagles/pnnl-ci/haero_Debug_double/include/spdlog/fmt/bundled/core.h(313): warning: unrecognized GCC pragma
> /qfs/projects/ops/rh7_gpu/gcc/10.2.0/include/c++/10.2.0/cmath(204): catastrophic error: error while writing generated C++ file: No space left on device
> 1 catastrophic error detected in the compilation of "/people/svceagles/gitlab/6197/haero_Debug_double/src/tests/aero_modes_tests.cpp".
> Compilation terminated.
> gmake[2]: *** [src/tests/CMakeFiles/aero_modes_unit_tests.dir/aero_modes_tests.cpp.o] Error 4
> gmake[1]: *** [src/tests/CMakeFiles/aero_modes_unit_tests.dir/all] Error 2
> /qfs/projects/eagles/pnnl-ci/haero_Debug_double/include/spdlog/fmt/bundled/core.h(313): warning: unrecognized GCC pragma
> In file included from tmpxft_000007fd_00000000-6_utils_unit_tests.cudafe1.stub.c:1:
> /tmp/tmpxft_000007fd_00000000-6_utils_unit_tests.cudafe1.stub.c:87:27: fatal error: error writing to /tmp/cch8T0k7.s: No space left on device
>    87 | #pragma GCC diagnostic pop
>       |                           ^
> compilation terminated.
> ```
> 
> The Release mode is compiling and most tests are passing but the job log is too long and I can't see after test 403 due to a huge printout of "input difference" in the validation test. I could potentially change the pipelines to run ctest non-verbosely then re-run failed tests with the verbose flag to prevent this in the future.

I'm not entirely sure what's going on because mam4xx w/ haero gpu/double/Debug compiles when I am running interactively on Deception but doesn't in CI. More debugging coming soon...

**Comment by jeff-cohere** [comment]
Yuck. It looks like something is seriously wrong with Deception's CUDA environment. From a failed build log:

```
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003596_00000000-7_aer_rad_props_lw.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003316_00000000-7_setrxt.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003564_00000000-7_update_aod_spec.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_000034f7_00000000-7_modal_size_parameters.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00002bc3_00000000-7_nlnmat.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_000032df_00000000-7_chm_diags.cpp1.ii: No such file or directory
<built-in>: fatal error: when writing output to /tmp/tmpxft_000027ce_00000000-7_compute_tendencies.cpp1.ii: No such file or directory
compilation terminated.
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cicc' core dumped
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003588_00000000-7_aer_rad_props_sw.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00002df2_00000000-7_cloud_mod.cpp1.ii: No such file or directory
<built-in>: fatal error: when writing output to /tmp/tmpxft_00002edf_00000000-7_lin_strat_chem_solve.cpp1.ii: No such file or directory
compilation terminated.
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_0000336a_00000000-7_table_photo.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003557_00000000-7_modal_aero_lw.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_00003595_00000000-7_hetfrz_rates_1box.cpp1.ii: No such file or directory
compilation terminated.
<built-in>: fatal error: when writing output to /tmp/tmpxft_000021ae_00000000-7_skywkr_gasaerexch_timestepping.cpp1.ii: No such file or directory
compilation terminated.
compilation terminated.
*** [src/validation/mo_chm_diags/CMakeFiles/mo_chm_diags_driver.dir/mo_chm_diags_driver.cpp.o] Error 1
```

**Comment by jeff-cohere** [comment]
Okay, it seems like the PNNL CI system still has issues. Meanwhile, I've verified that this PR builds and passes all tests with my local GPU build.

Does anyone object to merging this PR, since the failure is not related to mam4xx?

**Comment by jaelynlitz** [comment]
> Okay, it seems like the PNNL CI system still has issues. Meanwhile, I've verified that this PR builds and passes all tests with my local GPU build.
> 
> Does anyone object to merging this PR, since the failure is not related to mam4xx?

I am good with merging and will open an issue for the Deception CI problems

**Review by jeff-cohere — APPROVED** [review]

**Pull request merged**
