### PR TITLE
Upgrade to Ubuntu 22 for push mirror

### LINKED ISSUE #131: PNNL CI Ubuntu image needs upgrade
We're currently experiencing failures in our PNNL Push Mirror action (see, for example, [this PR](https://github.com/eagles-project/mam4xx/pull/120). The failures seem to be related to an "Ubuntu-18.04 brownout," which sounds like a stick to encourage us to update to a more recent Ubuntu image like 20.04 or 22.04.

@CameronRutherford , I know we already discussed this, and again, there's no hurry. But here's an issue you can close out when you have a chance to update the Ubuntu image used by the PNNL CI system.

### PR DESCRIPTION
**Pull request by CameronRutherford**
Closes #131 

cc @jeff-cohere @jaelynlitz

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Thanks, @CameronRutherford ! Any idea why the PNNL CI is failing? I only see:

```
      ++ rm /people/svceagles/gitlab/3902/haero_Release_double/jobid_1536527
exit $res
++ exit 2
Running after script...
$ export WORKDIR=$HOME/gitlab/${CI_PIPELINE_ID}/${WORKDIR_SUFFIX}
$ job_ids="$WORKDIR/jobid_*"
$ for job in $job_ids # collapsed multi-line command
$ rm -rf $WORKDIR
ERROR: Job failed: command terminated with exit code 2
```

etc

**Comment by jeff-cohere** [comment]
Aha, Kyle pointed out that Haero needs to be rebuilt, so he's doing that.

**Comment by CameronRutherford** [comment]
> Aha, Kyle pointed out that Haero needs to be rebuilt, so he's doing that.

It would be a bit of a hack, but I could do the following:
- keep hearo src code around that is used to build CI processes
- have haero build jobs run every time
  - clone hearo at the start of each job, and check if the commit sha is the same as the last built version
  - if identical, end job stage. If not identical, re-build haero and proceeded to testing

It just seems like HAERO needing a rebuild is quite a common occurrence, and I was trying to brainstorm ways of easing this... I was thinking of having the pipeline stage run based on a file being changed or some other condition, but there is;t a clear indication of that within the mam4xx repo itself.

**Comment by CameronRutherford** [comment]
> Thanks, @CameronRutherford ! Any idea why the PNNL CI is failing? I only see:
> 
> ```
>       ++ rm /people/svceagles/gitlab/3902/haero_Release_double/jobid_1536527
> exit $res
> ++ exit 2
> Running after script...
> $ export WORKDIR=$HOME/gitlab/${CI_PIPELINE_ID}/${WORKDIR_SUFFIX}
> $ job_ids="$WORKDIR/jobid_*"
> $ for job in $job_ids # collapsed multi-line command
> $ rm -rf $WORKDIR
> ERROR: Job failed: command terminated with exit code 2
> ```
> 
> etc

Unfortunately, you can't view full job logs... Would this be worth looking into? I am sure that there is a way to post artifacts from build to GitHub - perhaps I could post the full job log to GitHub whenever the pipeline fails?

**Comment by jeff-cohere** [comment]
Re: haero rebuilds--we're still in heavy-development mode on this project, so the only thing that I can tell you about the frequency of rebuilding Haero is: we're going to need it whenever we need it. :-)

Re: logs: if it's easy, it'd be nice to see build errors on GitHub, but if it takes a lot of work, I'm not sure it's worth the effort. Most of the errors that we encounter currently are false positives (backed up CI queues and stale Haero builds), so if we can address those issues, we might eliminate a lot of failed CI builds.

**Comment by jeff-cohere** [comment]
Good to merge!

**Review by jeff-cohere — APPROVED** [review]

**Comment by pressel** [comment]
For what it is worth, I'm fine with just manually rebuilding haero when we need to, it is not that hard to do and fairly obvious when it needs to be done.

**Pull request merged**
