### PR TITLE
remove non-ascii characters from mam4xx

### PR DESCRIPTION
**Pull request by mjs271**
Ran across a few of these lately and figured why not get rid of them. Most were in comments or something latex-y. And it appears that cmake doesn't get too grumpy about them.

### CODE REVIEW

**Review by pressel — APPROVED** [review]

**Comment by pressel** [comment]
I'm fine with merging this, but it looks like clang-format check is failing.

**Review by odiazib — APPROVED** [review]

**Comment by jeff-cohere** [comment]
@mjs271 , can you do a `clang-format` on this branch, and then we can merge it?

**Comment by mjs271** [comment]
After getting a clean `make format-cxx<-check>` on my system, I re-ran the test, and it looks like there was some sort of glitch in the matrix causing the `clang-format` image to not be found by the autotester. Passed on re-run, however.
```
Run jidicula/clang-format-action@v4.9.0
Run "/home/runner/work/_actions/jidicula/clang-format-action/v4.9.0/check.sh" "14" "src" "llvm" ""
Unable to find image 'ghcr.io/jidicula/clang-format:14' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/jidicula/clang-format/manifests/14": Get "https://ghcr.io/token?scope=repository%3Ajidicula%2Fclang-format%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
Failed on file: src/mam4xx/gasaerexch.hpp
```

**Comment by jeff-cohere** [comment]
Okay to merge!

**Pull request merged**
