### PR TITLE
mam_coupling- move code from eamxx to mam4xx

### PR DESCRIPTION
**Pull request by odiazib**
This PR makes a copy of the following functions from [mam_coupling](https://github.com/eagles-project/scream/blob/2d2180dfdd67eac8cf76efdb773428e6c0117181/components/eamxx/src/physics/mam/mam_coupling.hpp#L710) :

`transfer_prognostics_to_work_arrays`, `transfer_work_arrays_to_prognostics`,` convert_work_arrays_to_vmr`, and `convert_work_arrays_to_mmr`.

### CODE REVIEW

**Comment by odiazib** [comment]
we must merge this PR after PR #282

**Review by jeff-cohere — APPROVED** [review]
This looks good. Good idea to bring these into mam4xx!

**Comment by jeff-cohere** [comment]
I've merged in the changes from #282 and tested successfully on my own GPU.

**Comment by jeff-cohere** [comment]
The CPU tests have passed, and I've tested with a GPU, so I'm merging this one.

**Pull request merged**
