### PR TITLE
Trivial change to use aero_model::gas_pcnst.

### PR DESCRIPTION
**Pull request by overfelt**
The classes that set a gas_pcnst from aero_model::gas_pcnst in public header data were changed to use the one from aero_model directly. Clean up the code a bit.

Note that there is a gas_pcnst in gas_chemistry that is set to 31. The one in aero_model is set to 40 and it might be a bit confusing.

### CODE REVIEW

**Comment by singhbalwinder** [comment]
You are right, it is very confusing to call this variable "gas_pcnst" when it has space to store gasses and other constituents. In E3SM or EAM, it is called just `pcnst`. Would it be too much work to change it from `gas_pcnt` to `pcnst`?

I reviewed the PR and it looks good to me.

**Comment by overfelt** [comment]
It is easy to change aero_model::gas_pcnst to aero_model::pcnst.  Looking through the code we have
```
./modal_aer_opt.hpp:constexpr int pcnst = 40;
./water_uptake.hpp:constexpr int nvars = 40;
./ndrop.hpp:constexpr int nvars = 40;
./ndrop.hpp:constexpr int nvar_ptend_q = 40;

and the one we just created:
./aero_model.hpp:static constexpr int gas_pcnst = 40;
```
I assume these are different names for gss_pcnst and should also be replaced?

**Comment by singhbalwinder** [comment]
Thanks, James! Yes, it would be great if we can unify them all into one and call it `pcnst`.

**Comment by overfelt** [comment]
@singhbalwinder , seems the new changes to this pull request triggered a new review request when you have time.

**Review by singhbalwinder — APPROVED** [review]
Looks great! Thanks, James for taking care of this. This has been bothering me and I am happy that it is all consistent now.

**Pull request merged**
