### PR TITLE
Creates unit test that causes chemistry solver to fail

### PR DESCRIPTION
**Pull request by mjs271**
This is a small/simple one.

This PR tests three cases for the chemistry solver used in `gaschem_[...].hpp`.
1. Standard, hard-coded tolerance of 1.0e-3 => all cells converge.
2. Extremely small tolerance of ~~1.0e-200~~ 1.0e-35 => all cells fail to converge.
  - Updated to fit the tolerance into single precision.
4. Middle-ground tolerance of 1.0e-17 => some cells converge, and others do not.

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Hey Mike! What do you intend with this PR? Is it ready for review yet, or are you still working on it?

**Comment by mjs271** [comment]
It was intended to be a quick/easy merge, but I'm having trouble diagnosing the autotest failure... it's returning a lot of zero residuals that should not be zeros.
<details>

<summary>Here's the test output on my local Mac</summary>

```
Output:
----------------------------------------------------------
Calling initialize_kokkos
 ExecSpace name: Threads
 ExecSpace initialized: yes
 active avx set: 
 compiler id: GCC
 FPE support is disabled
 #host threads: 1

Starting catch session on rank 0 out of 1
[2023-09-18 10:34:27.826] [gaschem unit tests] [debug] ===============================================
[2023-09-18 10:34:27.826] [gaschem unit tests] [debug] ***gas chem unit tests Case 1: full converge***
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] ===============================================
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] case 1 error tolerance = 0.001
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 0 and max_delta[0] = 2.5272695856476137e-11
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 1 and max_delta[1] = 9.526618236750188e-12
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 2 and max_delta[2] = 9.526698777962019e-12
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 3 and max_delta[3] = 5.9711572708374934e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 4 and max_delta[4] = 1.695214637859485e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 5 and max_delta[5] = 2.6944458146469178e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 6 and max_delta[6] = 9.828096974990429e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 7 and max_delta[7] = 4.0820182996011203e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 8 and max_delta[8] = 4.962210765903074e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 9 and max_delta[9] = 1.0922819905227219e-16
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 10 and max_delta[10] = 5.484318201426311e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 11 and max_delta[11] = 3.5555349886255555e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 12 and max_delta[12] = 7.146877708074077e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 13 and max_delta[13] = 3.588680554428007e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 14 and max_delta[14] = 2.4332564241667182e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 15 and max_delta[15] = 6.01110463520164e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 16 and max_delta[16] = 8.95461304304737e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 17 and max_delta[17] = 1.8113683414510266e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 18 and max_delta[18] = 7.40572884575539e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 19 and max_delta[19] = 5.2798565621706945e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 20 and max_delta[20] = 4.613144710019458e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 21 and max_delta[21] = 8.100644258548671e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 22 and max_delta[22] = 3.0883543292437365e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 23 and max_delta[23] = 2.6623923844519786e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 24 and max_delta[24] = 3.1745237176654314e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 25 and max_delta[25] = 4.958980848566325e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 26 and max_delta[26] = 3.609062957025964e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 27 and max_delta[27] = 3.7387967253911727e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 28 and max_delta[28] = 0
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 29 and max_delta[29] = 6.426301647109229e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] 0 entries failed to converge
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] ===============================================
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] 
 **gas chem unit tests Case 2: full failure**
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] ===============================================
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] case 2 error tolerance = 1e-35
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 0 and max_delta[0] = 2.600208330355756e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 1 and max_delta[1] = 4.3169248975156994e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 2 and max_delta[2] = 2.4551926144040136e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 3 and max_delta[3] = 5.9711572708374934e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 4 and max_delta[4] = 1.695214637859485e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 5 and max_delta[5] = 2.6944458146469178e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 6 and max_delta[6] = 9.828096974990429e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 7 and max_delta[7] = 4.0820182996011203e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 8 and max_delta[8] = 4.962210765903074e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 9 and max_delta[9] = 1.0922819905227219e-16
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 10 and max_delta[10] = 5.484318201426311e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 11 and max_delta[11] = 3.5555349886255555e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 12 and max_delta[12] = 7.146877708074077e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 13 and max_delta[13] = 3.588680554428007e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 14 and max_delta[14] = 2.4332564241667182e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 15 and max_delta[15] = 6.01110463520164e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 16 and max_delta[16] = 8.95461304304737e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 17 and max_delta[17] = 1.8113683414510266e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 18 and max_delta[18] = 7.40572884575539e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 19 and max_delta[19] = 5.2798565621706945e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 20 and max_delta[20] = 4.613144710019458e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 21 and max_delta[21] = 8.100644258548671e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 22 and max_delta[22] = 3.0883543292437365e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 23 and max_delta[23] = 2.6623923844519786e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 24 and max_delta[24] = 3.1745237176654314e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 25 and max_delta[25] = 4.958980848566325e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 26 and max_delta[26] = 3.609062957025964e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 27 and max_delta[27] = 3.7387967253911727e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 28 and max_delta[28] = 0
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 29 and max_delta[29] = 6.426301647109229e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] 30 entries failed to converge
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] ====================================================
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] 
 ***gas chem unit tests Case 3: partial failure***
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] ====================================================
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] case 3 error tolerance = 1e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 0 and max_delta[0] = 2.600208330355756e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 1 and max_delta[1] = 4.3169248975156994e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 2 and max_delta[2] = 2.4551926144040136e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 3 and max_delta[3] = 5.9711572708374934e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 4 and max_delta[4] = 1.695214637859485e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 5 and max_delta[5] = 2.6944458146469178e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Converged for i = 6 and max_delta[6] = 9.828096974990429e-18
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 7 and max_delta[7] = 4.0820182996011203e-17
[2023-09-18 10:34:27.827] [gaschem unit tests] [debug] Did not converge for i = 8 and max_delta[8] = 4.962210765903074e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 9 and max_delta[9] = 1.0922819905227219e-16
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Converged for i = 10 and max_delta[10] = 5.484318201426311e-18
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 11 and max_delta[11] = 3.5555349886255555e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 12 and max_delta[12] = 7.146877708074077e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 13 and max_delta[13] = 3.588680554428007e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 14 and max_delta[14] = 2.4332564241667182e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 15 and max_delta[15] = 6.01110463520164e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Converged for i = 16 and max_delta[16] = 8.95461304304737e-18
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 17 and max_delta[17] = 1.8113683414510266e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Converged for i = 18 and max_delta[18] = 7.40572884575539e-18
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 19 and max_delta[19] = 5.2798565621706945e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 20 and max_delta[20] = 4.613144710019458e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 21 and max_delta[21] = 8.100644258548671e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 22 and max_delta[22] = 3.0883543292437365e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 23 and max_delta[23] = 2.6623923844519786e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 24 and max_delta[24] = 3.1745237176654314e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 25 and max_delta[25] = 4.958980848566325e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 26 and max_delta[26] = 3.609062957025964e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 27 and max_delta[27] = 3.7387967253911727e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 28 and max_delta[28] = 0
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] Did not converge for i = 29 and max_delta[29] = 6.426301647109229e-17
[2023-09-18 10:34:27.828] [gaschem unit tests] [debug] 25 entries failed to converge
===============================================================================
All tests passed (3 assertions in 3 test cases)
```
</details>

<details>

<summary>Output from autotester</summary>

```
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] ===============================================
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] ***gas chem unit tests Case 1: full converge***
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] ===============================================
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] case 1 error tolerance = 0.001
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 0 and max_delta[0] = 7.403612e-08
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 1 and max_delta[1] = 1.2262697e-07
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 2 and max_delta[2] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 3 and max_delta[3] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 4 and max_delta[4] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 5 and max_delta[5] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 6 and max_delta[6] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 7 and max_delta[7] = 8.661703e-08
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 8 and max_delta[8] = 8.994798e-08
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 9 and max_delta[9] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 10 and max_delta[10] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 11 and max_delta[11] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 12 and max_delta[12] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 13 and max_delta[13] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 14 and max_delta[14] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 15 and max_delta[15] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 16 and max_delta[16] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 17 and max_delta[17] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 18 and max_delta[18] = 6.5223176e-08
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 19 and max_delta[19] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 20 and max_delta[20] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 21 and max_delta[21] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 22 and max_delta[22] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 23 and max_delta[23] = 7.32031e-08
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 24 and max_delta[24] = 0
13: [2023-09-15 19:32:33.070] [gaschem unit tests] [debug] Converged for i = 25 and max_delta[25] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 26 and max_delta[26] = 7.0892746e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 27 and max_delta[27] = 7.7466574e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 28 and max_delta[28] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 29 and max_delta[29] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] 0 entries failed to converge
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] ===============================================
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] 
13:  **gas chem unit tests Case 2: full failure**
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] ===============================================
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] case 2 error tolerance = 1e-35
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 0 and max_delta[0] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 1 and max_delta[1] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 2 and max_delta[2] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 3 and max_delta[3] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 4 and max_delta[4] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 5 and max_delta[5] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 6 and max_delta[6] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Did not converge for i = 7 and max_delta[7] = 8.6617035e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Did not converge for i = 8 and max_delta[8] = 8.994799e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 9 and max_delta[9] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 10 and max_delta[10] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 11 and max_delta[11] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 12 and max_delta[12] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 13 and max_delta[13] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 14 and max_delta[14] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 15 and max_delta[15] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 16 and max_delta[16] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 17 and max_delta[17] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Did not converge for i = 18 and max_delta[18] = 6.522317e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 19 and max_delta[19] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 20 and max_delta[20] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 21 and max_delta[21] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 22 and max_delta[22] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Did not converge for i = 23 and max_delta[23] = 7.3203104e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 24 and max_delta[24] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 25 and max_delta[25] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 26 and max_delta[26] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Did not converge for i = 27 and max_delta[27] = 7.746657e-08
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 28 and max_delta[28] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] Converged for i = 29 and max_delta[29] = 0
13: [2023-09-15 19:32:33.071] [gaschem unit tests] [debug] 5 entries failed to converge
```

</details>

**Comment by jeff-cohere** [comment]
Thanks for the explanation! Might be worth testing on a Linux box if you have one available.

**Comment by mjs271** [comment]
I'm closing this for now (or forever?) since trying to fix this has led to discovering even more weirdness in the gas chem solver that I need to figure out first.

**Pull request closed without merging**
