### PR TITLE
Fixes for Scream integration.

### PR DESCRIPTION
**Pull request by overfelt**
Scream does strong const checking of Kokkos views so modified the input only views of dropmixnuc to be const data.

Fix an index out-of-bounds error.

### CODE REVIEW

**Review by odiazib — APPROVED** [review]
It looks good to me.

**Comment by odiazib** [comment]
I do not see the test that runs in i/gitlab/code.pnnl.gov. @jeff-cohere

**Comment by jeff-cohere** [comment]
I think this was merged before those tests could report, so I don't know if we can do anything about it on this end. You can probably log into the [PNNL CI system](http://gitlab.pnnl.gov/), though, if you want to check the results there.

**Comment by overfelt** [comment]
Oh, thought I saw a green check mark that the tests had finished.

**Comment by jeff-cohere** [comment]
Okay, it looks like the pipeline is still running--we're just not getting the results reported. Here's the link to the pipeline (requires PNNL single-signon): https://code.pnnl.gov/e3sm/eagles/mam4xx/-/pipelines

**Pull request merged**
