### PR TITLE
Add Comments and Concerns to gas_chem, plus one minor fix

### PR DESCRIPTION
**Pull request by mjs271**
In an effort to create a case in which the Newton-Raphson solve in `gas_chem.hpp` fails, I ended up having to go through most of that file and also `gas_chem_mechanism.hpp` to get things straight in my own head. I added a bunch of explanatory comments and also some spots where computational weirdness appeared to be ocurring.

In doing that, I noticed that, from a perspective of units consistency, there are some very strange-looking arithmetic calculations being done. I put a `FIXME` at the ones I spotted along with some salient details. Note that, it's ***possible*** that everything is ok, but that would seem to require the `base_solution`, `solution`, etc., arrays to be carrying quantities with differing units and/or the same for the reaction rates (`lrxt`, `rxt`) or washout rates(?) (`lhet`, `het_rates`) arrays. This would be in conflict with comments from MAM4 that define:
```
lrxt := rxt rates [1/cm^3/s]
lhet := washout rates [1/s]
solution := species mixing ratios [vmr]
```

Other than that, fixed what appears to be [one tiny transcription error](https://github.com/eagles-project/mam4xx/blob/d2412e536cdb444be51f15ae4a014b4e2b1186d4/src/mam4xx/gas_chem.hpp#L357). I would be surprised if that resulted in failing tests, but I suppose we'll see...

### CODE REVIEW

**Comment by odiazib** [comment]
We need to consider that constants in gas chemistry have units. These constants do not have simple units, they depend on the order of the reaction.

**Comment by mjs271** [comment]
That makes sense. I clearly just put my head down and took the old comments at face value. I suppose in the mean time, we give MAM4 the benefit of the doubt and assume things are correct.

I'll nix the comments tomorrow--thanks Oscar!

**Comment by singhbalwinder** [comment]
Thanks @mjs271 for digging into these issues! Tagging @tangshuaiqi, @brigaudet, and @mingxuanwupnnl as they might clarify some of these unit mismatches.

**Comment by mjs271** [comment]
After talking this over with Oscar and Jeff, I've changed the added `FIXME`s to `TODO`s and will make a record of this in a separate issue.

I do agree with @odiazib and @brigaudet that it's likely all of the units do check out. However, we eventually need to reconcile the comments with the math operations occurring in the code, but that's a problem for the future versions of ourselves (Hi! 👋), once porting work is finished. I would also argue that if certain elements in these reaction-rate or species qoi (vmr, mmr, number conc) arrays have different units from the rest of the elements, they should be in a separate array at least until the point that the same operation is being performed on the disparate quantities--e.g., the final Newton solve.

So, if I don't hear anything in the next day or so, I will merge this in.

**Review by odiazib — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]

**Review by singhbalwinder — APPROVED** [review]

**Pull request merged**
