### PR TITLE
Added code coverage instrumentation and reporting

### LINKED ISSUE #67: Add code coverage analysis to CI builds
We have been talking/worrying a lot recently about the code coverage in our MAM4 parameterizations, and it turns out there are some simple tools we can use to analyze this. I will add support for [codecov.io](https://about.codecov.io) to our CI workflow.

### PR DESCRIPTION
**Pull request by jeff-cohere**
Closes #67

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Now that this repo is public, code coverage reporting works! If we get this merged, we can fiddle with the coverage reporting settings.

**Comment by overfelt** [comment]
Are there instructions on how to run Lcov in our own project to get a detailed listing of what lines of code we are missing?

**Comment by overfelt** [comment]
The link worked for me. Ohh, nucleation is bringing us down!  But there is a mismatch between the marked lines and the source code for nucleation.hpp.  Comments are marked as not covered and such.  Maybe the wrong version was marked up?

**Comment by jeff-cohere** [comment]
I don't know. I think we should merge this to get something working (so all the tools work with the flawed assumptions of their authors) and then we can try to find out what's going on. :-)

**Review by overfelt — APPROVED** [review]

**Comment by overfelt** [comment]
I don't have any problem with merging and fixing later.

**Comment by jeff-cohere** [comment]
By the way, it looks like this workflow doesn't work yet on Macs, so that's another thing we need to fiddle with. I'd prefer to get this in first, though, so we can at least un-confuse CodeCov.

**Review by pressel — APPROVED** [review]

**Review by odiazib — APPROVED** [review]
I open issue #129, but this can be solved after merging this branch to main.

**Pull request merged**
